version: '3'

services:
  frontend: #Vue.js
    container_name: frontend
    build: ./container/frontend
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
        - ./src:/src:cached
        - node_modules:/src/node_modules
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
